import type { PublicSignalPulse } from "../../types/publicPulse";

function isoNowMinusMinutes(m: number) {
  return new Date(Date.now() - m * 60_000).toISOString();
}

const ANON = [
  "B2B Infra Startup",
  "Energy Systems Co",
  "AI DevTools Startup",
  "Robotics Infra Startup",
  "FinOps Platform",
  "Grid Software Startup",
  "Security SaaS Startup",
  "Climate Infra Startup",
];

export function buildMockPublicPulses(): PublicSignalPulse[] {
  return [
    {
      pulseId: "p-001",
      computedAt: isoNowMinusMinutes(18),
      isAnonymized: true,
      displayName: ANON[0],
      category: "Infrastructure",
      stageBand: "Seed",
      momentum: "Warming",
      timingWindow: "Opening",
      alignmentBefore: 67,
      alignmentAfter: 74,
      readinessBefore: 62,
      readinessAfter: 70,
      triggerSignals: ["Narrative Coherence ↑", "Product Velocity ↑"],
      unlockedInvestorsCount: 18,
      investorClass: "Seed",
      recommendedAction: { title: "Reframe narrative toward infrastructure thesis", probabilityDeltaPct: 9 },
    },
    {
      pulseId: "p-002",
      computedAt: isoNowMinusMinutes(41),
      isAnonymized: true,
      displayName: ANON[2],
      category: "AI DevTools",
      stageBand: "Seed",
      momentum: "Surge",
      timingWindow: "Active",
      alignmentBefore: 71,
      alignmentAfter: 82,
      readinessBefore: 66,
      readinessAfter: 76,
      triggerSignals: ["Product Velocity ↑", "Team Composition ↑"],
      unlockedInvestorsCount: 27,
      investorClass: "Seed",
      recommendedAction: { title: "Showcase senior engineering hires", probabilityDeltaPct: 6 },
    },
    {
      pulseId: "p-003",
      computedAt: isoNowMinusMinutes(63),
      isAnonymized: true,
      displayName: ANON[1],
      category: "Energy Infra",
      stageBand: "Early A",
      momentum: "Stable",
      timingWindow: "Opening",
      alignmentBefore: 59,
      alignmentAfter: 66,
      readinessBefore: 58,
      readinessAfter: 64,
      triggerSignals: ["Customer Proof ↑"],
      unlockedInvestorsCount: 12,
      investorClass: "Early A",
      recommendedAction: { title: "Strengthen customer proof", probabilityDeltaPct: 14 },
    },
    {
      pulseId: "p-004",
      computedAt: isoNowMinusMinutes(92),
      isAnonymized: true,
      displayName: ANON[7],
      category: "Climate",
      stageBand: "Seed",
      momentum: "Warming",
      timingWindow: "Active",
      alignmentBefore: 73,
      alignmentAfter: 79,
      readinessBefore: 68,
      readinessAfter: 73,
      triggerSignals: ["Capital Rotation →", "Category Momentum ↑"],
      unlockedInvestorsCount: 14,
      investorClass: "Seed",
      recommendedAction: { title: "Target these 18 seed funds first", probabilityDeltaPct: 8 },
    },
    {
      pulseId: "p-005",
      computedAt: isoNowMinusMinutes(125),
      isAnonymized: true,
      displayName: ANON[5],
      category: "Energy Infra",
      stageBand: "Seed",
      momentum: "Warming",
      timingWindow: "Opening",
      alignmentBefore: 64,
      alignmentAfter: 72,
      readinessBefore: 60,
      readinessAfter: 69,
      triggerSignals: ["Customer Proof ↑", "Traction Shape →"],
      unlockedInvestorsCount: 19,
      investorClass: "Seed",
      recommendedAction: { title: "Strengthen customer proof", probabilityDeltaPct: 14 },
    },
    {
      pulseId: "p-006",
      computedAt: isoNowMinusMinutes(152),
      isAnonymized: true,
      displayName: ANON[3],
      category: "Robotics",
      stageBand: "Pre-Seed",
      momentum: "Stable",
      timingWindow: "Opening",
      alignmentBefore: 55,
      alignmentAfter: 62,
      readinessBefore: 52,
      readinessAfter: 58,
      triggerSignals: ["Technical Depth ↑"],
      unlockedInvestorsCount: 9,
      investorClass: "Pre-Seed",
      recommendedAction: { title: "Shift positioning: Tool → Platform", probabilityDeltaPct: 7 },
    },
    {
      pulseId: "p-007",
      computedAt: isoNowMinusMinutes(188),
      isAnonymized: true,
      displayName: ANON[4],
      category: "FinOps",
      stageBand: "Series A",
      momentum: "Cooling",
      timingWindow: "Closing",
      alignmentBefore: 70,
      alignmentAfter: 66,
      readinessBefore: 74,
      readinessAfter: 71,
      triggerSignals: ["Timing Alignment ↓"],
      unlockedInvestorsCount: 0,
      investorClass: "Series A",
      recommendedAction: { title: "Delay Series A outreach", probabilityDeltaPct: 11 },
    },
    {
      pulseId: "p-008",
      computedAt: isoNowMinusMinutes(230),
      isAnonymized: true,
      displayName: ANON[6],
      category: "Security",
      stageBand: "Seed",
      momentum: "Surge",
      timingWindow: "Active",
      alignmentBefore: 69,
      alignmentAfter: 80,
      readinessBefore: 63,
      readinessAfter: 75,
      triggerSignals: ["Narrative Coherence ↑", "Product Velocity ↑"],
      unlockedInvestorsCount: 22,
      investorClass: "Seed",
      recommendedAction: { title: "Reframe narrative toward infrastructure thesis", probabilityDeltaPct: 9 },
    },
  ];
}
