'use strict';

/**
 * Canonical default signal weights — SSOT for dimension caps, class weights, feed priority.
 * Admin overrides stored in signal_weight_config (DB) merge on top of these defaults.
 */

const DIMENSION_KEYS = [
  'founder_language_shift',
  'investor_receptivity',
  'news_momentum',
  'capital_convergence',
  'execution_velocity',
];

const DEFAULT_SIGNAL_WEIGHT_CONFIG = {
  version: 'signals_v2',
  totalCap: 10,
  dimensionCaps: {
    founder_language_shift: 2.0,
    investor_receptivity: 2.5,
    news_momentum: 1.5,
    capital_convergence: 2.0,
    execution_velocity: 2.0,
  },
  dimensionClassWeights: {
    founder_language_shift: {
      founder_psychology_signal: 1.0,
      founder_excellence_signal: 0.95,
      founder_cunning_signal: 0.9,
      customer_delight_signal: 0.88,
      talent_magnet_signal: 0.85,
      failure_learning_signal: 0.82,
      failure_exit_signal: 0.35,
      exploratory_signal: 1.0,
      product_signal: 0.9,
      market_position_signal: 0.8,
      gtm_signal: 0.8,
      expansion_signal: 0.6,
      buyer_signal: 0.5,
      exit_signal: 0.5,
    },
    investor_receptivity: {
      fundraising_signal: 1.0,
      revenue_signal: 0.9,
      growth_signal: 0.85,
      acquisition_signal: 0.8,
      enterprise_signal: 0.75,
      demand_signal: 0.7,
      efficiency_signal: 0.65,
      distress_signal: 0.3,
      failure_exit_signal: 0.25,
    },
    capital_convergence: {
      fundraising_signal: 1.0,
      diligence_signal: 0.95,
      acquisition_signal: 0.9,
      exit_signal: 0.85,
      revenue_signal: 0.75,
      growth_signal: 0.65,
      distress_signal: 0.4,
    },
    execution_velocity: {
      product_signal: 1.0,
      hiring_signal: 0.9,
      gtm_hiring_signal: 0.92,
      engineering_hiring_signal: 0.91,
      growth_signal: 0.85,
      expansion_signal: 0.8,
      partnership_signal: 0.75,
      gtm_signal: 0.7,
      demand_signal: 0.6,
    },
  },
  newsSourceWeights: {
    execution_signals: 0.85,
    web_signals: 0.65,
    rss_scrape: 1.0,
    sec_edgar: 0.85,
    llm_enrichment: 0.35,
    social_signal: 0.45,
    description: 0.0,
    pitch: 0.0,
    problem: 0.0,
    solution: 0.0,
    value_proposition: 0.0,
    tagline: 0.0,
    market: 0.0,
    founder_upload: 0.0,
    structured_metrics: 0.0,
  },
  /** Feed ranking priority — used by lib/signalScorer.js */
  classPriorityWeights: {
    fundraising_signal: 2.0,
    acquisition_signal: 2.0,
    exit_signal: 1.9,
    distress_signal: 1.8,
    revenue_signal: 1.8,
    investor_interest_signal: 1.7,
    investor_rejection_signal: 1.5,
    regulatory_signal: 1.5,
    market_position_signal: 1.4,
    product_signal: 1.4,
    founder_psychology_signal: 1.35,
    founder_excellence_signal: 1.25,
    failure_learning_signal: 1.2,
    failure_exit_signal: 1.15,
    talent_magnet_signal: 1.2,
    founder_cunning_signal: 1.1,
    customer_delight_signal: 1.1,
    hiring_signal: 1.3,
    enterprise_signal: 1.2,
    expansion_signal: 1.2,
    gtm_signal: 1.1,
    demand_signal: 1.1,
    growth_signal: 1.0,
    partnership_signal: 1.0,
    efficiency_signal: 0.9,
    infrastructure_signal: 0.8,
    exploratory_signal: 0.6,
    unclassified_signal: 0.3,
  },
};

module.exports = { DEFAULT_SIGNAL_WEIGHT_CONFIG, DIMENSION_KEYS };
