import {
  confidenceLabel,
  getPrimaryVariants,
  type InvestorEmailProfile,
} from "@/lib/emailInference";

export interface InvestorProfileExport {
  rank: number;
  name: string;
  firm: string;
  role: string;
  sectors: string[];
  stage: string;
  checkSize: string;
  matchScore: number;
  signalScore: number;
  isSuperMatch?: boolean;
  whyYouMatchTags?: string[];
  reason: string;
  investmentThesis?: string;
  recentActivity?: string;
  emailProfile?: InvestorEmailProfile;
  knownEmail?: string;
}

export interface InvestorProfilesExportOptions {
  startupName: string;
  startupUrl: string;
  godScore?: number | null;
  investors: InvestorProfileExport[];
}

export function sanitizeExportFilename(name: string): string {
  const base = name.replace(/[^a-z0-9]+/gi, "_").replace(/^_|_$/g, "") || "startup";
  return `${base}_top_investor_matches`;
}

function bulletList(items: string[]): string {
  return items.filter(Boolean).map((item) => `- ${item}`).join("\n");
}

export function buildInvestorProfilesMarkdown(options: InvestorProfilesExportOptions): string {
  const { startupName, startupUrl, godScore, investors } = options;
  const generatedAt = new Date().toISOString();
  const domain = startupUrl.replace(/^https?:\/\//i, "").replace(/\/.*$/, "");

  const lines: string[] = [
    `# PYTHIA Investor Match Report`,
    ``,
    `**Startup:** ${startupName}`,
    `**Website:** ${startupUrl}`,
    `**Domain:** ${domain}`,
  ];

  if (godScore != null && Number.isFinite(godScore)) {
    lines.push(`**GOD score:** ${Math.round(godScore)} / 100`);
  }

  lines.push(
    `**Investors included:** ${investors.length}`,
    `**Generated:** ${generatedAt}`,
    ``,
    `---`,
    ``,
    `Review these top-ranked investor profiles offline. Match order reflects PYTHIA timing × thesis fit × signal score.`,
    ``,
  );

  for (const inv of investors) {
    lines.push(`## #${inv.rank} — ${inv.name}`);
    lines.push(``);
    lines.push(`| Field | Detail |`);
    lines.push(`| --- | --- |`);
    lines.push(`| Firm | ${inv.firm} |`);
    lines.push(`| Role | ${inv.role} |`);
    lines.push(`| Match score | ${inv.matchScore}/100 |`);
    lines.push(`| Signal score | ${inv.signalScore} |`);
    lines.push(`| Stage focus | ${inv.stage} |`);
    lines.push(`| Check size | ${inv.checkSize} |`);
    lines.push(`| Sectors | ${inv.sectors.join(", ") || "—"} |`);
    if (inv.isSuperMatch) {
      lines.push(`| Super match | Yes |`);
    }
    lines.push(``);

    if (inv.whyYouMatchTags?.length) {
      lines.push(`### Match signals`);
      lines.push(bulletList(inv.whyYouMatchTags));
      lines.push(``);
    }

    lines.push(`### PYTHIA reasoning`);
    lines.push(inv.reason || "—");
    lines.push(``);

    const thesis = inv.investmentThesis || inv.recentActivity;
    if (thesis) {
      lines.push(`### Investment thesis`);
      lines.push(thesis);
      lines.push(``);
    }

    if (inv.knownEmail) {
      lines.push(`### Known email`);
      lines.push(inv.knownEmail);
      lines.push(``);
    }

    if (inv.emailProfile) {
      const primary = getPrimaryVariants(inv.emailProfile);
      lines.push(`### PYTHIA email targets (${inv.emailProfile.domain})`);
      if (primary.length) {
        lines.push(bulletList(primary.map((v) => `${v.address} — ${confidenceLabel(v.confidence)} (${v.pattern})`)));
      } else {
        lines.push(`- ${inv.emailProfile.primaryEmail}`);
      }
      const pitchFallbacks = inv.emailProfile.variants
        .filter((v) => v.type === "pitch")
        .slice(0, 3)
        .map((v) => v.address);
      if (pitchFallbacks.length) {
        lines.push(``);
        lines.push(`Pitch fallbacks: ${pitchFallbacks.join(", ")}`);
      }
      lines.push(``);
    }

    lines.push(`---`);
    lines.push(``);
  }

  lines.push(
    `_Generated by PYTHIA on pythh.ai — for founder review only._`,
  );

  return lines.join("\n");
}

export function downloadInvestorProfilesMarkdown(options: InvestorProfilesExportOptions): void {
  if (!options.investors.length) return;

  const content = buildInvestorProfilesMarkdown(options);
  const blob = new Blob([content], { type: "text/markdown;charset=utf-8" });
  const objectUrl = URL.createObjectURL(blob);
  const anchor = document.createElement("a");
  anchor.href = objectUrl;
  anchor.download = `${sanitizeExportFilename(options.startupName)}.md`;
  anchor.style.display = "none";
  document.body.appendChild(anchor);
  anchor.click();
  document.body.removeChild(anchor);
  URL.revokeObjectURL(objectUrl);
}
