/**
 * SignalReadinessBrief.tsx (Final Form)
 * 
 * The founder's armor — confidence without arrogance.
 * This is what founders show co-founders, advisors, and eventually investors.
 * 
 * Structure (exact spec):
 *   1. Header: "Signal Readiness Brief — Pythh" + "Market-aligned signal assessment"
 *   2. Signal Profile: Startup, Category, Lens, Strength, Timing, Persistence, Volatility
 *   3. Active Strategy: Title + Interpretation
 *   4. Precedent: Condensed founder stories
 *   5. What This Communicates to Investors: 3 bullet interpretation
 *   6. Footer: "Generated by Pythh"
 * 
 * Sharing: Default private, share link read-only, founder chooses to show/anonymize
 */

import React, { useState, useRef } from 'react';
import { Download, Share2, X, Eye, EyeOff, Copy, Check, Sparkles, Users, Shield } from 'lucide-react';
import type { StrategyInstance } from './StrategyBlock';

// ═══════════════════════════════════════════════════════════════
// TYPES
// ═══════════════════════════════════════════════════════════════

interface SignalProfile {
  startupName: string;
  category: string;
  lens_id: string;
  strength: number;
  timing_state: string;
  persistence_days: number;
  volatility: 'low' | 'medium' | 'high';
}

interface ReadinessBriefProps {
  signal: SignalProfile;
  strategy: StrategyInstance;
  onClose?: () => void;
  onExport?: () => void;
}

// ═══════════════════════════════════════════════════════════════
// STYLING
// ═══════════════════════════════════════════════════════════════

const LENS_LABELS: Record<string, string> = {
  sequoia: 'Sequoia Capital',
  yc: 'Y Combinator',
  a16z: 'Andreessen Horowitz',
  foundersfund: 'Founders Fund',
  greylock: 'Greylock Partners',
};

const TIMING_LABELS: Record<string, string> = {
  warming: 'Warming',
  prime: 'Prime',
  cooling: 'Cooling',
};

const VOLATILITY_LABELS: Record<string, string> = {
  low: 'Low',
  medium: 'Medium',
  high: 'High',
};

// ═══════════════════════════════════════════════════════════════
// MAIN COMPONENT
// ═══════════════════════════════════════════════════════════════

export default function SignalReadinessBrief({
  signal,
  strategy,
  onClose,
  onExport,
}: ReadinessBriefProps) {
  const cardRef = useRef<HTMLDivElement>(null);
  const [anonymize, setAnonymize] = useState(false);
  const [copied, setCopied] = useState(false);
  
  const dateStr = new Date().toLocaleDateString('en-US', { month: 'short', day: 'numeric', year: 'numeric' });
  
  // Condense precedents for the brief
  const condensedPrecedents = (strategy.precedents || []).slice(0, 2).map(p => {
    // Extract key action from the precedent
    const sentences = p.split('. ');
    if (sentences.length >= 2) {
      return sentences.slice(0, 2).join('. ') + '.';
    }
    return p.length > 120 ? p.slice(0, 120) + '...' : p;
  });
  
  // Generate investor interpretation based on signal state
  const getInvestorInterpretation = () => {
    const bullets = [];
    
    // Timing interpretation
    if (signal.timing_state === 'warming') {
      bullets.push('Founder understands timing and restraint');
    } else if (signal.timing_state === 'prime') {
      bullets.push('Founder is acting within optimal window');
    } else {
      bullets.push('Founder demonstrates market awareness');
    }
    
    // Persistence interpretation
    if (signal.persistence_days >= 14) {
      bullets.push('Momentum appears durable, not event-driven');
    } else {
      bullets.push('Early signals showing consistency');
    }
    
    // Strategy interpretation
    bullets.push('Fundraising approach reflects market awareness');
    
    return bullets;
  };
  
  const handleCopyLink = () => {
    const shareUrl = `${window.location.origin}/brief/${strategy.id}${anonymize ? '?anon=1' : ''}`;
    navigator.clipboard.writeText(shareUrl);
    setCopied(true);
    setTimeout(() => setCopied(false), 2000);
  };
  
  const handleExport = () => {
    if (onExport) onExport();
    window.print();
  };

  return (
    <div className="fixed inset-0 z-50 flex items-center justify-center p-4 bg-black/90 backdrop-blur-sm">
      <div 
        ref={cardRef}
        className="w-full max-w-xl bg-[#0a0a0a] rounded-xl border border-zinc-800 overflow-hidden shadow-2xl"
        style={{ fontFamily: 'Inter, system-ui, sans-serif' }}
      >
        {/* Print styles */}
        <style>{`
          @media print {
            body * { visibility: hidden; }
            .readiness-brief, .readiness-brief * { visibility: visible; }
            .readiness-brief { position: absolute; left: 0; top: 0; width: 100%; background: white; color: black; }
            .no-print { display: none !important; }
          }
        `}</style>
        
        {/* ═══════════════════════════════════════════════════════════════
            HEADER
        ═══════════════════════════════════════════════════════════════ */}
        <div className="px-6 py-5 border-b border-zinc-800/50">
          <div className="flex items-center justify-between">
            <div>
              <div className="flex items-center gap-2 mb-1">
                <Shield className="w-4 h-4 text-cyan-400" />
                <span className="text-sm font-semibold text-white">
                  Signal Readiness Brief
                </span>
                <span className="text-sm text-zinc-500">—</span>
                <span className="text-sm font-semibold text-cyan-400">Pythh</span>
              </div>
              <div className="text-xs text-zinc-500">
                Market-aligned signal assessment
              </div>
            </div>
            
            <div className="flex items-center gap-2 no-print">
              <button
                onClick={() => setAnonymize(!anonymize)}
                className={`p-2 rounded-lg transition-colors ${anonymize ? 'bg-amber-500/10 text-amber-400' : 'bg-zinc-800 text-zinc-500 hover:text-white'}`}
                title={anonymize ? 'Show startup name' : 'Hide startup name'}
              >
                {anonymize ? <EyeOff className="w-4 h-4" /> : <Eye className="w-4 h-4" />}
              </button>
              
              {onClose && (
                <button
                  onClick={onClose}
                  className="p-2 text-zinc-500 hover:text-white hover:bg-zinc-800 rounded-lg transition-colors"
                >
                  <X className="w-4 h-4" />
                </button>
              )}
            </div>
          </div>
        </div>
        
        {/* ═══════════════════════════════════════════════════════════════
            CONTENT
        ═══════════════════════════════════════════════════════════════ */}
        <div className="p-6 space-y-6 readiness-brief">
          
          {/* SECTION 1: Signal Profile */}
          <div>
            <div className="text-[10px] uppercase tracking-widest text-zinc-600 mb-4">
              Signal Profile
            </div>
            
            <div className="grid grid-cols-2 gap-x-8 gap-y-3">
              <div>
                <div className="text-[10px] text-zinc-500 mb-0.5">Startup</div>
                <div className="text-sm text-white font-medium">
                  {anonymize ? 'Stealth Startup' : signal.startupName}
                </div>
              </div>
              
              <div>
                <div className="text-[10px] text-zinc-500 mb-0.5">Category</div>
                <div className="text-sm text-white">{signal.category}</div>
              </div>
              
              <div>
                <div className="text-[10px] text-zinc-500 mb-0.5">Lens</div>
                <div className="text-sm text-white">{LENS_LABELS[signal.lens_id] || signal.lens_id}</div>
              </div>
              
              <div>
                <div className="text-[10px] text-zinc-500 mb-0.5">Signal Strength</div>
                <div className="text-sm text-white">
                  {signal.strength} <span className="text-zinc-500">(steady)</span>
                </div>
              </div>
              
              <div>
                <div className="text-[10px] text-zinc-500 mb-0.5">Timing State</div>
                <div className="text-sm text-white">{TIMING_LABELS[signal.timing_state] || signal.timing_state}</div>
              </div>
              
              <div>
                <div className="text-[10px] text-zinc-500 mb-0.5">Persistence</div>
                <div className="text-sm text-white">{signal.persistence_days} days</div>
              </div>
              
              <div className="col-span-2">
                <div className="text-[10px] text-zinc-500 mb-0.5">Volatility</div>
                <div className="text-sm text-white">{VOLATILITY_LABELS[signal.volatility] || signal.volatility}</div>
              </div>
            </div>
          </div>
          
          {/* SECTION 2: Active Strategy */}
          <div className="pt-5 border-t border-zinc-800/50">
            <div className="text-[10px] uppercase tracking-widest text-zinc-600 mb-4">
              Active Strategy
            </div>
            
            <div className="space-y-3">
              <div>
                <div className="text-[10px] text-zinc-500 mb-1">Strategy</div>
                <div className="text-sm text-white font-medium">{strategy.title}</div>
              </div>
              
              <div>
                <div className="text-[10px] text-zinc-500 mb-1">Interpretation</div>
                <p className="text-sm text-zinc-300 leading-relaxed">
                  {strategy.interpretation || strategy.description}
                </p>
              </div>
            </div>
          </div>
          
          {/* SECTION 3: Precedent */}
          {condensedPrecedents.length > 0 && (
            <div className="pt-5 border-t border-zinc-800/50">
              <div className="text-[10px] uppercase tracking-widest text-zinc-600 mb-4">
                Precedent
              </div>
              
              <ul className="space-y-2">
                {condensedPrecedents.map((p, i) => (
                  <li key={i} className="flex items-start gap-2">
                    <span className="text-zinc-600 mt-0.5">•</span>
                    <p className="text-sm text-zinc-400 leading-relaxed">{p}</p>
                  </li>
                ))}
              </ul>
            </div>
          )}
          
          {/* SECTION 4: What This Communicates to Investors */}
          <div className="pt-5 border-t border-zinc-800/50">
            <div className="text-[10px] uppercase tracking-widest text-zinc-600 mb-4">
              Investor Interpretation
            </div>
            
            <ul className="space-y-2">
              {getInvestorInterpretation().map((point, i) => (
                <li key={i} className="flex items-start gap-2">
                  <span className="text-zinc-600 mt-0.5">•</span>
                  <p className="text-sm text-zinc-300">{point}</p>
                </li>
              ))}
            </ul>
          </div>
          
          {/* FOOTER */}
          <div className="pt-5 border-t border-zinc-800/50 flex items-center justify-between">
            <div className="text-xs text-zinc-600">
              Generated by <span className="text-cyan-400 font-semibold">Pythh</span>
            </div>
            <div className="text-xs text-zinc-600">
              {dateStr}
            </div>
          </div>
        </div>
        
        {/* ═══════════════════════════════════════════════════════════════
            ACTION BAR
        ═══════════════════════════════════════════════════════════════ */}
        <div className="px-6 py-4 border-t border-zinc-800/50 flex items-center justify-between no-print bg-zinc-900/50">
          <div className="flex items-center gap-3">
            <button
              onClick={handleCopyLink}
              className="flex items-center gap-2 px-4 py-2 bg-zinc-800 hover:bg-zinc-700 text-zinc-300 text-xs font-medium rounded-lg transition-colors"
            >
              {copied ? <Check className="w-3.5 h-3.5 text-emerald-400" /> : <Share2 className="w-3.5 h-3.5" />}
              {copied ? 'Copied!' : 'Share (read-only)'}
            </button>
            
            {anonymize && (
              <span className="text-[10px] text-amber-400/70">
                Link will hide startup name
              </span>
            )}
          </div>
          
          <button
            onClick={handleExport}
            className="flex items-center gap-2 px-4 py-2 bg-cyan-500/10 hover:bg-cyan-500/20 text-cyan-400 text-xs font-medium rounded-lg border border-cyan-500/20 transition-colors"
          >
            <Download className="w-3.5 h-3.5" />
            Export PDF
          </button>
        </div>
      </div>
    </div>
  );
}

// ═══════════════════════════════════════════════════════════════
// TRIGGER BUTTON
// ═══════════════════════════════════════════════════════════════

interface BriefTriggerProps {
  signal: SignalProfile;
  strategy: StrategyInstance;
  className?: string;
}

export function ReadinessBriefTrigger({ signal, strategy, className = '' }: BriefTriggerProps) {
  const [isOpen, setIsOpen] = useState(false);
  
  // Only show if there's an active strategy with sufficient signal strength
  if (strategy.status !== 'active' || signal.strength < 40) {
    return null;
  }
  
  return (
    <>
      <button
        onClick={() => setIsOpen(true)}
        className={`
          flex items-center gap-1.5 px-3 py-1.5 rounded-lg
          text-[11px] text-cyan-400 hover:text-cyan-300
          bg-cyan-500/10 hover:bg-cyan-500/15
          border border-cyan-500/20 hover:border-cyan-500/30
          transition-all ${className}
        `}
      >
        <Sparkles className="w-3 h-3" />
        Generate Readiness Brief
      </button>
      
      {isOpen && (
        <SignalReadinessBrief
          signal={signal}
          strategy={strategy}
          onClose={() => setIsOpen(false)}
        />
      )}
    </>
  );
}
