/**
 * FeedbackWidget — thumbs up / thumbs down rating for a PYTHIA analysis run.
 *
 * States:
 *  1. Idle        — two thumb buttons visible, no selection
 *  2. Thumbs-up   — emerald highlight; optional comment icon to expand textarea
 *  3. Thumbs-down — amber highlight; reason chip selector appears immediately;
 *                   optional comment textarea below the chips
 *  4. Submitted   — "Saved" confirmation; rating / reason can still be changed
 *
 * The parent passes a `runId` (UUID) and the component handles the tRPC
 * mutation internally. On mount it also queries for any existing feedback
 * so the widget restores its state across page navigations.
 */
import { useState, useEffect, useRef } from "react";
import { ThumbsUp, ThumbsDown, MessageSquare, Check, Loader2 } from "lucide-react";
import { trpc } from "@/lib/trpc";
import { toast } from "sonner";

// ─── Reason catalogue ─────────────────────────────────────────────────────────

/** Must match the z.enum in server/routers.ts pipeline.submitFeedback */
export type DownReason =
  | "wrong_investors"
  | "inaccurate_scores"
  | "missing_sectors"
  | "poor_summary"
  | "wrong_stage"
  | "other";

const REASON_LABELS: Record<DownReason, string> = {
  wrong_investors: "Wrong investors",
  inaccurate_scores: "Inaccurate scores",
  missing_sectors: "Missing sectors",
  poor_summary: "Poor summary",
  wrong_stage: "Wrong stage",
  other: "Other",
};

const REASON_KEYS = Object.keys(REASON_LABELS) as DownReason[];

// ─── Props ────────────────────────────────────────────────────────────────────

interface FeedbackWidgetProps {
  /** UUID identifying the analysis run — generated by the parent before calling analyzeStartup */
  runId: string;
  /** Whether the analysis has finished (widget is disabled while scanning) */
  ready?: boolean;
}

// ─── Component ────────────────────────────────────────────────────────────────

export default function FeedbackWidget({ runId, ready = true }: FeedbackWidgetProps) {
  const [selected, setSelected] = useState<"up" | "down" | null>(null);
  const [reason, setReason] = useState<DownReason | null>(null);
  const [submitted, setSubmitted] = useState(false);
  const [showComment, setShowComment] = useState(false);
  const [comment, setComment] = useState("");
  const textareaRef = useRef<HTMLTextAreaElement>(null);

  // Restore existing feedback on mount
  const { data: existing } = trpc.pipeline.getFeedback.useQuery(
    { runId },
    { enabled: !!runId && ready }
  );

  useEffect(() => {
    if (existing) {
      setSelected(existing.rating);
      setReason((existing.reason as DownReason | null) ?? null);
      setComment(existing.comment ?? "");
      setSubmitted(true);
    }
  }, [existing]);

  const submitFeedback = trpc.pipeline.submitFeedback.useMutation({
    onSuccess: () => {
      setSubmitted(true);
      setShowComment(false);
    },
    onError: () => {
      toast.error("Couldn't save your feedback. Please try again.");
    },
  });

  const isPending = submitFeedback.isPending;

  // ── Handlers ────────────────────────────────────────────────────────────────

  function handleThumb(rating: "up" | "down") {
    if (!ready || isPending) return;

    // Clicking the already-selected thumb toggles the comment box
    if (selected === rating && submitted) {
      setShowComment((v) => !v);
      return;
    }

    setSelected(rating);
    setSubmitted(false);
    setShowComment(false);

    if (rating === "up") {
      // For thumbs-up: clear any previous reason and auto-submit immediately
      setReason(null);
      submitFeedback.mutate({ runId, rating, reason: undefined });
    }
    // For thumbs-down: don't auto-submit yet — wait for the user to pick a reason
    // (or they can skip and the form will submit on comment submit / reason chip click)
  }

  function handleReason(r: DownReason) {
    if (!ready || isPending) return;
    const newReason = reason === r ? null : r; // toggle off if same chip clicked
    setReason(newReason);
    // When "Other" is selected, expand the comment box and focus it
    if (newReason === "other") {
      setShowComment(true);
    }
    // Auto-submit with the selected reason (comment stays as-is)
    submitFeedback.mutate({
      runId,
      rating: "down",
      reason: newReason ?? undefined,
      comment: comment.trim() || undefined,
    });
  }

  // Focus the textarea after it mounts when "Other" is selected
  useEffect(() => {
    if (showComment && reason === "other" && textareaRef.current) {
      // Small delay so the element is fully rendered before focus
      const id = setTimeout(() => textareaRef.current?.focus(), 50);
      return () => clearTimeout(id);
    }
  }, [showComment, reason]);

  function handleSubmitComment(e: React.FormEvent) {
    e.preventDefault();
    if (!selected) return;
    submitFeedback.mutate({
      runId,
      rating: selected,
      reason: reason ?? undefined,
      comment: comment.trim() || undefined,
    });
  }

  // ── Render ──────────────────────────────────────────────────────────────────

  return (
    <div className="mt-3">
      {/* Row: label + thumb buttons */}
      <div className="flex items-center gap-3 flex-wrap">
        <span
          className="text-xs font-medium tracking-wide"
          style={{ color: "oklch(0.5 0.01 264)" }}
        >
          Was this analysis helpful?
        </span>

        <div className="flex items-center gap-1.5">
          {/* Thumbs Up */}
          <button
            type="button"
            disabled={!ready || isPending}
            onClick={() => handleThumb("up")}
            aria-label="Rate analysis helpful"
            aria-pressed={selected === "up"}
            className="flex items-center justify-center w-8 h-8 rounded-lg border transition-all duration-150 disabled:opacity-40 disabled:cursor-not-allowed"
            style={{
              borderColor: selected === "up" ? "oklch(0.696 0.17 162.48)" : "oklch(0.28 0.01 264)",
              backgroundColor: selected === "up" ? "oklch(0.696 0.17 162.48 / 0.15)" : "transparent",
            }}
            onMouseEnter={(e) => {
              if (selected !== "up") {
                (e.currentTarget as HTMLElement).style.borderColor = "oklch(0.696 0.17 162.48 / 0.6)";
                (e.currentTarget as HTMLElement).style.backgroundColor = "oklch(0.696 0.17 162.48 / 0.08)";
              }
            }}
            onMouseLeave={(e) => {
              if (selected !== "up") {
                (e.currentTarget as HTMLElement).style.borderColor = "oklch(0.28 0.01 264)";
                (e.currentTarget as HTMLElement).style.backgroundColor = "transparent";
              }
            }}
          >
            <ThumbsUp
              size={14}
              style={{ color: selected === "up" ? "oklch(0.696 0.17 162.48)" : "oklch(0.55 0.01 264)" }}
            />
          </button>

          {/* Thumbs Down */}
          <button
            type="button"
            disabled={!ready || isPending}
            onClick={() => handleThumb("down")}
            aria-label="Rate analysis not helpful"
            aria-pressed={selected === "down"}
            className="flex items-center justify-center w-8 h-8 rounded-lg border transition-all duration-150 disabled:opacity-40 disabled:cursor-not-allowed"
            style={{
              borderColor: selected === "down" ? "oklch(0.769 0.188 70.08)" : "oklch(0.28 0.01 264)",
              backgroundColor: selected === "down" ? "oklch(0.769 0.188 70.08 / 0.12)" : "transparent",
            }}
            onMouseEnter={(e) => {
              if (selected !== "down") {
                (e.currentTarget as HTMLElement).style.borderColor = "oklch(0.769 0.188 70.08 / 0.6)";
                (e.currentTarget as HTMLElement).style.backgroundColor = "oklch(0.769 0.188 70.08 / 0.08)";
              }
            }}
            onMouseLeave={(e) => {
              if (selected !== "down") {
                (e.currentTarget as HTMLElement).style.borderColor = "oklch(0.28 0.01 264)";
                (e.currentTarget as HTMLElement).style.backgroundColor = "transparent";
              }
            }}
          >
            <ThumbsDown
              size={14}
              style={{ color: selected === "down" ? "oklch(0.769 0.188 70.08)" : "oklch(0.55 0.01 264)" }}
            />
          </button>

          {/* Comment toggle (after any rating is selected) */}
          {selected && (
            <button
              type="button"
              onClick={() => setShowComment((v) => !v)}
              aria-label="Add a comment"
              className="flex items-center justify-center w-8 h-8 rounded-lg border transition-all duration-150"
              style={{
                borderColor: showComment ? "oklch(0.5 0.01 264)" : "oklch(0.28 0.01 264)",
                backgroundColor: showComment ? "oklch(0.5 0.01 264 / 0.1)" : "transparent",
              }}
            >
              <MessageSquare size={13} style={{ color: "oklch(0.5 0.01 264)" }} />
            </button>
          )}

          {/* Pending spinner */}
          {isPending && (
            <Loader2 size={14} className="animate-spin" style={{ color: "oklch(0.5 0.01 264)" }} />
          )}

          {/* Saved confirmation */}
          {submitted && !isPending && (
            <span className="flex items-center gap-1 text-xs" style={{ color: "oklch(0.696 0.17 162.48)" }}>
              <Check size={12} />
              Saved
            </span>
          )}
        </div>
      </div>

      {/* ── Thumbs-down: reason chip selector ─────────────────────────────── */}
      {selected === "down" && (
        <div className="mt-3">
          <p className="text-xs mb-2" style={{ color: "oklch(0.5 0.01 264)" }}>
            What was the issue? <span style={{ color: "oklch(0.38 0.01 264)" }}>(optional)</span>
          </p>
          <div className="flex flex-wrap gap-1.5">
            {REASON_KEYS.map((r) => {
              const isActive = reason === r;
              return (
                <button
                  key={r}
                  type="button"
                  disabled={isPending}
                  onClick={() => handleReason(r)}
                  aria-pressed={isActive}
                  className="text-xs px-2.5 py-1 rounded-full border transition-all duration-150 disabled:opacity-40 disabled:cursor-not-allowed"
                  style={{
                    borderColor: isActive ? "oklch(0.769 0.188 70.08)" : "oklch(0.28 0.01 264)",
                    backgroundColor: isActive ? "oklch(0.769 0.188 70.08 / 0.15)" : "transparent",
                    color: isActive ? "oklch(0.769 0.188 70.08)" : "oklch(0.55 0.01 264)",
                  }}
                  onMouseEnter={(e) => {
                    if (!isActive) {
                      (e.currentTarget as HTMLElement).style.borderColor = "oklch(0.769 0.188 70.08 / 0.5)";
                      (e.currentTarget as HTMLElement).style.color = "oklch(0.769 0.188 70.08 / 0.8)";
                    }
                  }}
                  onMouseLeave={(e) => {
                    if (!isActive) {
                      (e.currentTarget as HTMLElement).style.borderColor = "oklch(0.28 0.01 264)";
                      (e.currentTarget as HTMLElement).style.color = "oklch(0.55 0.01 264)";
                    }
                  }}
                >
                  {REASON_LABELS[r]}
                </button>
              );
            })}
          </div>
        </div>
      )}

      {/* ── Optional comment form ──────────────────────────────────────────── */}
      {showComment && (
        <form onSubmit={handleSubmitComment} className="mt-3">
          <textarea
            ref={textareaRef}
            value={comment}
            onChange={(e) => setComment(e.target.value)}
            placeholder={
              selected === "up"
                ? "What made this analysis useful? (optional)"
                : "Tell PYTHIA more about the issue… (optional)"
            }
            maxLength={500}
            rows={3}
            className="w-full text-sm rounded-lg px-3 py-2 resize-none outline-none transition-colors duration-150 placeholder:text-sm"
            style={{
              backgroundColor: "oklch(0.18 0.01 264)",
              border: "1px solid oklch(0.28 0.01 264)",
              color: "oklch(0.85 0.005 264)",
            }}
            onFocus={(e) => {
              (e.currentTarget as HTMLElement).style.borderColor = "oklch(0.696 0.17 162.48 / 0.5)";
            }}
            onBlur={(e) => {
              (e.currentTarget as HTMLElement).style.borderColor = "oklch(0.28 0.01 264)";
            }}
          />
          <div className="flex items-center justify-between mt-2">
            <span className="text-xs" style={{ color: "oklch(0.4 0.01 264)" }}>
              {comment.length}/500
            </span>
            <div className="flex gap-2">
              <button
                type="button"
                onClick={() => setShowComment(false)}
                className="text-xs px-3 py-1.5 rounded-md transition-colors duration-150"
                style={{ color: "oklch(0.5 0.01 264)" }}
              >
                Cancel
              </button>
              <button
                type="submit"
                disabled={isPending}
                className="text-xs font-semibold px-3 py-1.5 rounded-md transition-all duration-150 disabled:opacity-50"
                style={{
                  backgroundColor: "oklch(0.696 0.17 162.48)",
                  color: "oklch(0.1 0.01 162)",
                }}
              >
                {isPending ? "Saving…" : "Submit"}
              </button>
            </div>
          </div>
        </form>
      )}
    </div>
  );
}
